version: '3.1'

services:
    api:
        image: almercadito-api-restful:1.0.0
        restart: always
        environment: 
            MODULE_CLIENTS_SPREADSHEET_ID: 123
            MODULE_CLIENTS_SPREADSHEET_PAGE: Clients
            MODULE_CLIENTES_SPREADSHEET_RANGE: A2:I
            GIN_MODE: release
        volumes:
            - ./credential:/app/credential
        ports:
            - "7070:8080"
